keys:
  - &master age1taay9m94a34sumrxpjfsgpddtcpuqlyyyyltpzz74l39ud7su42sm8duc5
  - &users:
     - &hailst0rm age157g7epkrpckjv6axncdcc8cktcfft43ntu5kqwmtc9t0mhuraglsgk76zm
  - &hosts:
    - &Nix-Laptop age1zatq4sksr9udwa4kd49m9xhyd60zux96vz6qhr4w67c4kknh648qzzzqkl
    - &Nix-Workstation age1w6cuzu3nca36jjs9yxnlgxe58nveezmr3sk2p6u0uec5dx4jjq2qwm0u3j
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *master
      - *hailst0rm
      - *Nix-Laptop
      - *Nix-Workstation
