# Configure regular AutoRecon options at the top of this file.

nmap = '-vv --reason -Pn -T5 --min-rate=5000 --min-parallelism=5000'
verbose = 1
ignore-plugin-checks = 1

# This includes all default plugins
tags = 'default,unsafe'

# Configure global options here.
[global]
username-wordlist = '/home/hailst0rm/cyber/wordlists/seclists/Usernames/cirt-default-usernames.txt'
password-wordlist = '/home/hailst0rm/cyber/wordlists/rockyou.txt'

# Configure plugin options here.
[dirbuster]
threads = 50
recursive = true
ext = 'html,txt,xml,php,aspx,pdf,js,doc,docx,jpg,png,config,asp,jsp'
wordlist = [
	# '/home/hailst0rm/cyber/wordlists/seclists/Discovery/Web-Content/common.txt',
	# '/home/hailst0rm/cyber/wordlists/seclists/Discovery/Web-Content/big.txt',
	'/home/hailst0rm/cyber/wordlists/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt'
]

[enum4linux]
tool = 'enum4linux-ng'

[onesixtyone]
community-strings = '/home/hailst0rm/cyber/wordlists/seclists/Discovery/SNMP/common-snmp-community-strings-onesixtyone.txt'

[subdomain]
wordlist = [
  '/home/hailst0rm/cyber/wordlists/seclists/Discovery/DNS/subdomains-top1million-110000.txt'
]
threads = 50
