agent:
    deadbeefcafe:
        autobind: true
        interface: ligolo
interface:
    ligolo:
        routes:
            - 10.4.133.0/24
web:
    behindreverseproxy: false
    corsallowedorigin:
        - https://webui.ligolo.ng
    debug: false
    enabled: true
    enableui: true
    listen: 127.0.0.1:8080
    logfile: ui.log
    secret: bb53f59a62c90cfcca1ecac85dcaf5f7fb77c0b408f4ac1479d0a812ef1227b4
    tls:
        alloweddomains: []
        autocert: false
        certfile: ""
        enabled: true
        keyfile: ""
        selfcert: true
        selfcertdomain: ligolo
    trustedproxies:
        - 127.0.0.1
    users:
        hailst0rm: $argon2id$v=19$m=32768,t=3,p=4$qNH0qyDoB/0lvUgkwECN+Q$MddsAiVmEHyt18SPJbqBRJ/7W0vBKZYK7M/gtagwhQc
