# Paygen Configuration Files
recipes_dir: /mnt/nas/Code/paygen-recipes/recipes
preprocessors_dir: /mnt/nas/Code/paygen-recipes/preprocessors
ps_obfuscation_yaml: /mnt/nas/Code/paygen-recipes/ps-obfuscation.yaml
ps_features_yaml: /mnt/nas/Code/paygen-recipes/ps-features.yaml
shellcodes_config: /mnt/nas/Code/paygen-recipes/shellcodes.yaml
output_dir: ~/cyber/postex-tools/payloads

# Build preferences
keep_source_files: true # If true, save rendered source code alongside compiled binaries
show_build_debug: true # If true, show real-time command output in build popup

# Web
web_host: '0.0.0.0'
web_port: 1337
web_debug: false